definitions:
  policy.Context:
    additionalProperties: true
    type: object
info:
  contact: {}
paths:
  /arm/selection:
    post:
      consumes:
      - application/json
      description: Select the arm based on the experiment policy.
      parameters:
      - description: Context Data
        in: body
        name: context
        required: true
        schema:
          $ref: '#/definitions/policy.Context'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: select arm
      tags:
      - arm-selector
swagger: "2.0"
